install.packages("shiny")
install.packages("data.table")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("plotly")
install.packages("shinydashboard")
install.packages("shinyWidgets")
install.packages("devtools")
install.packages("utils")
install.packages("leaflet")
devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
install.packages('RPostgres')
install.packages("DBI")