create table imoveisolx_transformed (
 id int,
 categoria varchar(255),
 tipo varchar(255),
 quartos int,
 banheiros int,
 vagas_garagem int,
 detalhes_imovel text,
 detalhes_condominio text,
 cep varchar(10),
 cidade varchar(255),
 estado varchar(2),
 bairro varchar(255),
 preco float,
 url text,
 operacao varchar(255),
 created_at varchar(255));